# Generated by Django 5.2.7 on 2025-10-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parameters_no', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('fasting', models.CharField(blank=True, max_length=100, null=True)),
                ('sample', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parameters', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
