# Generated by Django 5.2.7 on 2025-10-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasonal_pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('features', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='color',
        ),
        migrations.RemoveField(
            model_name='package',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='package',
            name='features',
        ),
        migrations.RemoveField(
            model_name='package',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='package',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='tests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='tests_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
