# Generated by Django 5.2.7 on 2025-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_seasonal_pack_remove_package_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonal_pack',
            old_name='features',
            new_name='tests',
        ),
        migrations.RemoveField(
            model_name='seasonal_pack',
            name='color',
        ),
        migrations.AddField(
            model_name='seasonal_pack',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonal_pack',
            name='tests_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
