# Generated by Django 5.2.7 on 2025-10-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_rename_features_seasonal_pack_tests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
