# Generated by Django 5.2.7 on 2025-10-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_test_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='body_structure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
