# Generated by Django 5.2.7 on 2025-10-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_package_body_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='body_structure',
        ),
        migrations.AddField(
            model_name='test',
            name='body_structure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
