# Generated by Django 5.2.7 on 2025-10-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_package_body_structure_test_body_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='package',
            name='fasting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='reportTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='sample',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seasonal_pack',
            name='reportTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='reportTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
