# Generated by Django 5.2.7 on 2025-11-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_remove_test_is_popular_package_fasting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='parameters_no',
            new_name='Booking',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='sample',
            new_name='Recommend',
        ),
    ]
