# Generated by Django 5.2.7 on 2025-11-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_rename_parameters_no_test_booking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='Booking',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='Recommend',
            new_name='recommend',
        ),
    ]
