# Generated by Django 5.2.7 on 2025-11-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_rename_booking_test_booking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='booking',
            new_name='parameter_no',
        ),
    ]
