# Generated by Django 5.2.7 on 2025-11-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_rename_booking_test_parameter_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='parameter_no',
            new_name='parameters_no',
        ),
    ]
