# Generated by Django 5.2.7 on 2025-11-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_rename_parameter_no_test_parameters_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='tests_no',
            new_name='parameters_no',
        ),
        migrations.RenameField(
            model_name='seasonal_pack',
            old_name='tests_no',
            new_name='parameters_no',
        ),
    ]
