# Generated by Django 4.2.14 on 2025-12-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0013_rename_tests_no_package_parameters_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Body_structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="package",
            name="body_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tests.body_structure",
            ),
        ),
        migrations.RenameField(
            model_name="test",
            old_name="body_structure",
            new_name="body_structure_old",
        ),
        migrations.AddField(
            model_name="test",
            name="body_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tests.body_structure",
            ),
        ),
    ]
