# Generated by Django 4.2.14 on 2025-12-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0014_body_structure_package_body_structure_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="body_structure_old",
        ),
    ]
