# Generated by Django 4.2.14 on 2025-12-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0015_remove_test_body_structure_old"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="body_structure",
        ),
        migrations.RemoveField(
            model_name="test",
            name="body_structure",
        ),
        migrations.AddField(
            model_name="package",
            name="body_structure",
            field=models.ManyToManyField(blank=True, to="tests.body_structure"),
        ),
        migrations.AddField(
            model_name="test",
            name="body_structure",
            field=models.ManyToManyField(blank=True, to="tests.body_structure"),
        ),
    ]
